# Generated by Django 4.2.6 on 2023-12-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt', models.CharField(max_length=100)),
                ('sname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
