# Generated by Django 4.2.6 on 2023-12-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='capname',
            field=models.CharField(default='amaravathi', max_length=100),
        ),
    ]
